package sergio.sastre.composable.preview.scanner.core.scanner.config

import io.github.classgraph.ClassGraph
import io.github.classgraph.ScanResult
import sergio.sastre.composable.preview.scanner.core.scanner.config.classpath.Classpath
import sergio.sastre.composable.preview.scanner.core.scanner.config.classpath.previewfinder.ClasspathPreviewsFinder
import sergio.sastre.composable.preview.scanner.core.scanner.config.classpath.previewfinder.ClasspathPreviewsFinderWithResult
import sergio.sastre.composable.preview.scanner.core.scanner.logger.PreviewScanningLogger
import sergio.sastre.composable.preview.scanner.core.scanresult.RequiresLargeHeap
import sergio.sastre.composable.preview.scanner.core.scanresult.filter.ScanResultFilter
import sergio.sastre.composable.preview.scanner.core.scanresult.filter.ScanResultFilterWithResult
import java.io.File
import java.io.InputStream

open class ClassGraphSourceScannerWithResult<T, R>(
    private val classGraph: ClassGraph,
    private val findComposableWithPreviewsInClass: ClasspathPreviewsFinderWithResult<T, R>,
    private val classpath: Classpath?,
    private val isLoggingEnabled: Boolean
) : SourceScannerWithResult<T, R> {

    private var updatedClassGraph = classGraph

    private val previewScanningLogger = PreviewScanningLogger().apply {
        enableLogging(isLoggingEnabled)
        addPreviewAnnotationName(findComposableWithPreviewsInClass.annotationToScanClassName)
        classpath?.apply { addSourceSetInfo(this) }
    }

    /**
     * Scan previews in all packages, including those of external dependencies.
     */
    @RequiresLargeHeap
    override fun scanAllPackages(): ScanResultFilterWithResult<T, R> {
        previewScanningLogger.useScanningSourceAllPackages()
        val scanResult = previewScanningLogger.measureScanningTimeAndGetResult {
            updatedClassGraph.scan()
        }
        return ScanResultFilterWithResult(
            scanResult,
            findComposableWithPreviewsInClass,
            previewScanningLogger
        )
    }

    /**
     * Scan previews in the given packageTrees
     *
     * @param packageTrees where we want to scan previews
     */
    override fun scanPackageTrees(vararg packageTrees: String): ScanResultFilterWithResult<T, R> {
        require(packageTrees.isNotEmpty()) {
            "packageTrees must not be empty. For that, use scanAllPackages() instead"
        }
        previewScanningLogger.useScanningSourcePackageTrees(*packageTrees)
        updatedClassGraph = updatedClassGraph.acceptPackages(*packageTrees)
        val scanResult = previewScanningLogger.measureScanningTimeAndGetResult {
            updatedClassGraph.scan()
        }
        return ScanResultFilterWithResult(
            scanResult,
            findComposableWithPreviewsInClass,
            previewScanningLogger
        )
    }

    /**
     * Scan previews in the given ‘include‘ packageTrees, excluding the 'exclude' packageTrees
     *
     * @param include where we want to scan previews
     * @param exclude where we do not want to scan previews, even though they were inside the included packageTrees
     */
    override fun scanPackageTrees(
        include: List<String>,
        exclude: List<String>
    ): ScanResultFilterWithResult<T, R> {
        if (include.isEmpty()) {
            throw IllegalArgumentException("include packages must not be empty. For that, use scanAllPackages() instead")
        }
        previewScanningLogger.useScanningSourcePackageTrees(included = include, excluded = exclude)
        updatedClassGraph = updatedClassGraph
            .acceptPackages(*include.toTypedArray())
            .rejectPackages(*exclude.toTypedArray())
        val scanResult = previewScanningLogger.measureScanningTimeAndGetResult {
            updatedClassGraph.scan()
        }
        return ScanResultFilterWithResult(
            scanResult,
            findComposableWithPreviewsInClass,
            previewScanningLogger
        )
    }

    /**
     * Scan previews in the given file
     *
     * @param jsonFile a json file that was generated by using ScanResultDump.dumpScanResultToFile(fileName)
     */
    override fun scanFile(jsonFile: File): ScanResultFilterWithResult<T, R> {
        previewScanningLogger.useScanningSourceFile(jsonFile.name)
        val scanResult = previewScanningLogger.measureScanningTimeAndGetResult {
            ScanResult.fromJSON(jsonFile.bufferedReader().use { it.readLine() })
        }
        return ScanResultFilterWithResult(
            scanResult,
            findComposableWithPreviewsInClass,
            previewScanningLogger
        )
    }

    /**
     * Scan for previews in the given InputStream.
     *
     * @param targetInputStream to make them accessible in instrumentation tests, like getInstrumentation().context.assets.open(fileName).
     * Such file was generated previously by using ScanResultDump.dumpScanResultToFileInAssets(fileName)
     *
     * @param customPreviewsInfoInputStream to make custom previews defined in a dependency or module,
     * like those in "androidx.compose.ui.tooling.preview", available in instrumentation tests.
     * Such file was generated previously by using ScanResultDump.dumpScanResultToFileInAssets(customPreviewsPackageTrees, customPreviewsFileName)
     */
    override fun scanFile(
        targetInputStream: InputStream,
        customPreviewsInfoInputStream: InputStream
    ): ScanResultFilterWithResult<T, R> {
        val scanResult =
            ScanResult.fromJSON(targetInputStream.bufferedReader().use { it.readLine() })
        findComposableWithPreviewsInClass
            .applyCustomPreviewsScanResult(
                ScanResult.fromJSON(
                    customPreviewsInfoInputStream.bufferedReader().use { it.readLine() })
            )
        return ScanResultFilterWithResult(
            scanResult,
            findComposableWithPreviewsInClass,
            previewScanningLogger
        )
    }
}

class ClassGraphSourceScanner<T>(
    classGraph: ClassGraph,
    private val findComposableWithPreviewsInClass: ClasspathPreviewsFinder<T>,
    classpath: Classpath?,
    isLoggingEnabled: Boolean
) : ClassGraphSourceScannerWithResult<T, Unit>(
    classGraph = classGraph,
    findComposableWithPreviewsInClass = findComposableWithPreviewsInClass,
    classpath = classpath,
    isLoggingEnabled = isLoggingEnabled
), SourceScanner<T> {

    @RequiresLargeHeap
    override fun scanAllPackages(): ScanResultFilter<T> =
        super.scanAllPackages().toScanResultFilter()

    override fun scanPackageTrees(vararg packageTrees: String): ScanResultFilter<T> =
        super.scanPackageTrees(*packageTrees).toScanResultFilter()

    override fun scanPackageTrees(
        include: List<String>,
        exclude: List<String>
    ): ScanResultFilter<T> =
        super.scanPackageTrees(include, exclude).toScanResultFilter()

    override fun scanFile(jsonFile: File): ScanResultFilter<T> =
        super.scanFile(jsonFile).toScanResultFilter()

    override fun scanFile(
        targetInputStream: InputStream,
        customPreviewsInfoInputStream: InputStream
    ): ScanResultFilter<T> =
        super.scanFile(targetInputStream, customPreviewsInfoInputStream).toScanResultFilter()

    private fun ScanResultFilterWithResult<T, Unit>.toScanResultFilter(): ScanResultFilter<T> =
        ScanResultFilter(
            scanResult = scanResult,
            previewsFinder = findComposableWithPreviewsInClass,
            previewScanningLogger = previewScanningLogger
        )
}
