package sergio.sastre.composable.preview.scanner.android.screenshotid

import sergio.sastre.composable.preview.scanner.core.android.preview.screenshotid.AndroidPreviewScreenshotIdBuilder as CoreAndroidPreviewScreenshotIdBuilder

typealias AndroidPreviewScreenshotIdBuilder = CoreAndroidPreviewScreenshotIdBuilder
