blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/sergio-sastre/ComposablePreviewScanner/discussions
    about: Please ask questions and share ideas here.
