package sergio.sastre.composable.preview.scanner.core.scanner

import io.github.classgraph.ClassGraph
import io.github.classgraph.ScanResult
import sergio.sastre.composable.preview.scanner.core.scanner.classloader.classpath.Classpath
import sergio.sastre.composable.preview.scanner.core.scanner.classloader.classpath.previewfinder.ClasspathPreviewsFinder
import sergio.sastre.composable.preview.scanner.core.scanresult.RequiresLargeHeap
import sergio.sastre.composable.preview.scanner.core.scanresult.filter.ScanResultFilter
import java.io.File
import java.io.InputStream

/**
 * Core Component to scan for Previews
 * @param defaultPackageTreesOfCrossModuleCustomPreviews // TODO
 */
abstract class ComposablePreviewScanner<T>(
    private val findComposableWithPreviewsInClass: ClasspathPreviewsFinder<T>,
    private val defaultPackageTreesOfCrossModuleCustomPreviews: List<String> = emptyList()
) {

    private var updatedClassGraph = ClassGraph()
        .ignoreMethodVisibility()
        .enableClassInfo()
        .enableMethodInfo()
        .enableAnnotationInfo()
        .enableMemoryMapping()

    /**
     * Scan previews in all packages, including those of external dependencies.
     */
    @RequiresLargeHeap
    fun scanAllPackages(): ScanResultFilter<T> {
        return ScanResultFilter(
            updatedClassGraph.scan(),
            findComposableWithPreviewsInClass,
        )
    }

    /**
     * Scan previews in the given packageTrees
     *
     * @param packageTrees where we want to scan previews
     */
    fun scanPackageTrees(vararg packageTrees: String): ScanResultFilter<T> {
        if (packageTrees.isEmpty()) {
            throw IllegalArgumentException("packages must not be empty. For that, use scanAllPackages() instead")
        }
        updatedClassGraph = updatedClassGraph.acceptPackages(*packageTrees)
        return ScanResultFilter(
            updatedClassGraph.scan(),
            findComposableWithPreviewsInClass,
        )
    }

    /**
     * Scan previews in the given ‘include‘ packageTrees, excluding the 'exclude' packageTrees
     *
     * @param include where we want to scan previews
     * @param exclude where we do not want to scan previews, even though they were inside the included packageTrees
     */
    fun scanPackageTrees(include: List<String>, exclude: List<String>): ScanResultFilter<T> {
        if (include.isEmpty()) {
            throw IllegalArgumentException("include packages must not be empty. For that, use scanAllPackages() instead")
        }
        updatedClassGraph = updatedClassGraph
            .acceptPackages(*include.toTypedArray())
            .rejectPackages(*exclude.toTypedArray())
        return ScanResultFilter(
            updatedClassGraph.scan(),
            findComposableWithPreviewsInClass,
        )
    }

    /**
     * Scan previews from a sourceSet like 'screenshotTest' or 'androidTest', 'main' or a custom one via the given sourceSetClasspath
     *
     * @param sourceSetClasspath the classpath pointing to the package where compiled classes of a sourceSet are located
     * @param packageTreesOfCrossModuleCustomPreviews Package where you've defined custom Preview annotations that are present in this module as TRANSITIVE dependency.
     * As general rule, this can be left empty. Only use it if y
     */
    fun setTargetSourceSet(
        sourceSetClasspath: Classpath,
        packageTreesOfCrossModuleCustomPreviews: List<String> = emptyList()
    ) = apply {
        val absolutePath = File(sourceSetClasspath.buildDir, sourceSetClasspath.packagePath).absolutePath
        findComposableWithPreviewsInClass
            .applyOverridenClasspath(sourceSetClasspath.packagePath)
            .applyCrossModuleCustomPreviewPackageTrees(
                packageTreesOfCrossModuleCustomPreviews + defaultPackageTreesOfCrossModuleCustomPreviews
            )

        updatedClassGraph.overrideClasspath(absolutePath)
    }

    /**
     * Scan previews in the given file
     *
     * @param jsonFile a json file that was generated by using ScanResultDump.dumpScanResultToFile(fileName)
     */
    // TODO -> Allow to dump also customPreviews
    fun scanFile(jsonFile: File): ScanResultFilter<T> {
        val scanResult = ScanResult.fromJSON(jsonFile.bufferedReader().use { it.readLine() })
        return ScanResultFilter(
            scanResult,
            findComposableWithPreviewsInClass,
        )
    }

    /**
     * Scan for previews in the given InputStream.
     *
     * @param targetInputStream to support accessible by instrumentation tests, like getInstrumentation().context.assets.open(fileName).
     * Such file was generated previously by using ScanResultDump.dumpScanResultToFileInAssets(fileName)
     *
     */
    fun scanFile(
        targetInputStream: InputStream,
        customPreviewsInfoInputStream: InputStream
    ): ScanResultFilter<T> {
        val scanResult = ScanResult.fromJSON(targetInputStream.bufferedReader().use { it.readLine() })
        findComposableWithPreviewsInClass
            .applyCustomPreviewsScanResult(ScanResult.fromJSON(customPreviewsInfoInputStream.bufferedReader().use { it.readLine() }))
        return ScanResultFilter(
            scanResult,
            findComposableWithPreviewsInClass,
        )
    }
}