package sergio.sastre.composable.preview.scanner.android.device.domain

import sergio.sastre.composable.preview.scanner.core.android.preview.device.domain.RobolectricDeviceQualifierBuilder as CoreRobolectricDeviceQualifierBuilder

typealias RobolectricDeviceQualifierBuilder = CoreRobolectricDeviceQualifierBuilder
